language: node_js
before_script: npm install browserify -g
script: npm run build
deploy:
  - provider: s3
    access_key_id: "AKIA3J3WNVATD7C6BIEU"
    secure: "TZKonZ33CEg2/93TOjKDAo2XkAta4XkM33kNK65tQfJ8pxfcIQiJzI/c8WcBMw3R5zrC2R03nQiUa/rv9m/Ogm7vZWItkBQFnhEQ/U1l5e74a3nI5U6JKfoxqXwqtjVaXqkKDocGhicAt0INzj08vkPMdArhR/Qf2416f1T7NsTugGPAhS3vV2gGpMED9IZA7act7xFdJuFglJzJxK7XXJR5z2vmOzyxk82gBeIYQclOo9I5x+4Dgs9KIcLkFi9u3K2SVz5/ZIPC/SLnbCcOV/GNRsi8MjYlzofKIiYDVmm2/roKy0/+HqXaWPJwIcreRoMt0F5znVJ1mtOPy6JxNDF2x+KsGEzOwSl7s5tb4M59v5La4g4XrLMc6xfDxieV1Ah85P9xw4l5e9Q1Ulq2YYbSaO3svfd53lHWGRvIz1o2l8aTFlBP8Ua+mOFENnsTm00BgUs12U0KOEP9ASdwXJLCocrjd0Ibh3pc7Bv1pddrv/LejmPcEf6eGS8jPV8AKqGM2B7Iow3kWPYuInXlOBBDGbAeMoCsihAlDHQZRG626QmmPiQJELmLxFXZs4aAdixVtk+kJtYQnJavVhUQnG02OylJnyJeU7s+pnbbAClADWqESu8ef01su3/GCVy44ZrVt/oMh/vP4fCTfHbPix/CDO+Qbj9Q+osNdsc5RFY="
    bucket: "Saratetra"